Disable chpasswd step
For some reason, the chpasswd --root command, outside the arch-chroot
context is not working as it was last week.

I've tried running an older version of the script and custom package
and the result was the same. Probably it is due to some breaking change
or a bug introduced in the latest Arch Linux's packages versions as we
always run pacman -Sy to make sure we're installing updated packages.

The error message was:
chpasswd: (user lemuel) pam_chauthtok() failed, error:
Module is unknown

As an alternative, we can set up the user's password by running chpasswd
inside an arch-chroot context without the --root parameter.

Links:

- https://www.linuxquestions.org/questions/slackware-14/error-creating-lxc-container-on-current-4175677752/
- https://www.reddit.com/r/voidlinux/comments/l2nwhk/error_during_installation_it_wont_create_an_user/
- http://www.huge-man-linux.net/man8/chpasswd.html
- https://docs.jdcloud.com/en/virtual-machines/ssh-login-report-module-is-unknown

diff --git a/install b/install
--- a/install
+++ b/install
@@ -28,12 +28,13 @@ user=$(dialog --stdout --inputbox "Enter admin username" 0 0) || exit 1
 clear
 : "${user:?'user cannot be empty'}"
 
-password=$(dialog --stdout --passwordbox "Enter admin password" 0 0) || exit 1
-clear
-: "${password:?'password cannot be empty'}"
-password_confirmation=$(dialog --stdout --passwordbox "Enter admin password again" 0 0) || exit 1
-clear
-[[ "$password" == "$password_confirmation" ]] || ( echo "Passwords did not match"; exit 1; )
+# chpasswd: (user lemuel) pam_chauthtok failed, error: Module is unknown
+# password=$(dialog --stdout --passwordbox "Enter admin password" 0 0) || exit 1
+# clear
+# : "${password:?'password cannot be empty'}"
+# password_confirmation=$(dialog --stdout --passwordbox "Enter admin password again" 0 0) || exit 1
+# clear
+# [[ "$password" == "$password_confirmation" ]] || ( echo "Passwords did not match"; exit 1; )
 
 devicelist=$(lsblk -dplnx size -o name,size | grep -Ev "boot|rpmb|loop" | tac)
 # shellcheck disable=SC2086
@@ -114,8 +115,9 @@ arch-chroot /mnt useradd -mU -s /bin/bash -G wheel,docker "$user"
 arch-chroot /mnt chsh -s /bin/bash root
 arch-chroot /mnt chsh -s /bin/bash "$user"
 
-echo "$user:$password" | chpasswd --root /mnt
-echo "root:$password" | chpasswd --root /mnt
+# chpasswd: (user lemuel) pam_chauthtok failed, error: Module is unknown
+# echo "$user:$password" | chpasswd --root /mnt
+# echo "root:$password" | chpasswd --root /mnt
 
 arch-chroot /mnt systemctl enable NetworkManager.service
 arch-chroot /mnt systemctl enable docker.service
